spring:
  application:
    name: eureka-client
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hyh
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
spring:
  profiles: dev
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://hyh:123456@localhost:8761/eureka/



---
spring:
  profiles: test
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://hyh:123456@localhost:8761/eureka/

